package tests.troiaTester;

import java.net.MalformedURLException;

import org.apache.log4j.Logger;

import junit.framework.TestCase;
import main.com.troiaClient.TroiaRequest;
import main.com.troiaTester.AnalyzeResults;
import main.com.troiaTester.TestData;
import main.com.troiaTester.TestDataGenerator;
import main.com.troiaTester.TroiaAnalyzer;

/**
 * The class <code>TroiaAnalyzerTest</code> contains tests for the class {@link <code>TroiaAnalyzer</code>}
 * 
 * @pattern JUnit Test Case
 * 
 * @generatedBy CodePro at 7/31/12 11:43 AM
 * 
 * @author piotr.gnys@10clouds.com
 * 
 * @version $Revision$
 */
public class TroiaAnalyzerTest extends TestCase {

	/**
	 * Construct new test instance
	 * 
	 * @param name
	 *            the test name
	 */
	public TroiaAnalyzerTest(String name) {
		super(name);
	}

	/**
	 * Run the AnalyzeResults analyze(TroiaRequest, TestData, int) method test
	 */
	public void testAnalyzeWithTestData() {
		TroiaRequest request = null;
		try {
			request = new TroiaRequest(TROIA_URL, REQUEST_NAME, TIMEOUT);
		} catch (MalformedURLException e) {
			fail(e.getMessage());
		}
		TestData data = TestDataGenerator.getInstance().generateTestData(
				REQUEST_NAME, OBJECT_COUNT, CATEGORY_COUNT, WORKER_COUNT,
				MINIMUM_QUALITY, MAXIMUM_QUALITY, GOLD_RATIO, WORKERS_PER_OBJECT);
		TroiaAnalyzer analyzer = TroiaAnalyzer.getInstance();
		AnalyzeResults results;
		results = analyzer.analyze(request, data, DS_ITERATIONS);
		logger.info("Worker generated labels quality"+results.getSourceLabelQuality());
		logger.info("Troia generated labels quality"+results.getDawidSkeneLabelQuality());
	}

	private static final String REQUEST_NAME = "Analyzer Test";
	private static final String TROIA_URL = "http://localhost:8080/GetAnotherLabel/rest/";
	private static final int TIMEOUT = 200;
	private static final int OBJECT_COUNT = 2187;
	private static final int CATEGORY_COUNT = 3;
	private static final int WORKER_COUNT = 243;
	private static final double MINIMUM_QUALITY = 0;
	private static final double MAXIMUM_QUALITY = 1;
	private static final double GOLD_RATIO = 0.1;
	private static final int WORKERS_PER_OBJECT = 3;
	private static final int DS_ITERATIONS = 3;
	
	

	private static Logger logger = Logger.getLogger(TroiaAnalyzerTest.class);
}

/*
 * $CPS$ This comment was generated by CodePro. Do not edit it. patternId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern strategyId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = assertTrue = false callTestMethod = true createMain =
 * false createSetUp = false createTearDown = false createTestFixture = false
 * createTestStubs = false methods = analyze(QTroiaRequest;!QTestData;!I)
 * package = tests.dawidSkeneTester package.sourceFolder = TroiaJavaClient/src
 * superclassType = junit.framework.TestCase testCase = TroiaAnalyzerTest
 * testClassType = main.com.troiaTester.TroiaAnalyzer
 */