package tests.dawidSkeneTester;

import java.util.ArrayList;
import java.util.Collection;

import junit.framework.TestCase;
import main.com.dawidSkeneClient.Label;
import main.com.dawidSkeneTester.DSaSStressTest;

/**
 * The class <code>DSaSStressTestTest</code> contains tests for the class
 * {@link <code>DSaSStressTest</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 7/16/12 11:48 AM
 *
 * @author regule
 *
 * @version $Revision$
 */
public class DSaSStressTestTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public DSaSStressTestTest(String name) {
		super(name);
	}


	/**
	 * Run the Collection<String> generateObjects(int) method test
	 */
	public void testGenerateObjects()
	{
		DSaSStressTest fixture = new DSaSStressTest();
		int count = 10;
		fixture.setObjectsCount(count);
		Collection<String> result = fixture.generateObjects();
		for (String string : result) {
			System.out.println(string);
		}
	}
	/**
	 * Run the Collection<String> generateWorkers(int) method test
	 */
	public void testGenerateWorkers()
	{
		DSaSStressTest fixture = new DSaSStressTest();
		int count = 10;
		fixture.setWorkersCount(count);
		Collection<String> result = fixture.generateWorkers();
		for (String string : result) {
			System.out.println(string);
		}
	}
	
	/**
	 * Run the Collection<Label> generateLabels(ArrayList<String>,
	 * Collection<String>, Collection<String>) method test
	 */
	public void testGenerateLabels()
	{
		DSaSStressTest fixture = new DSaSStressTest();
		ArrayList<String> categories = new ArrayList<String>();
		categories.add("CategoryA");
		categories.add("CategoryB");
		categories.add("CategoryC");
		categories.add("CategoryD");
		fixture.setObjectsCount(10);
		fixture.setWorkersCount(10);
		Collection<String> workers = fixture.generateObjects();
		Collection<String> objects = fixture.generateWorkers();
		Collection<Label> result = fixture.generateLabels(categories, workers, objects);
		for (Label label : result) {
			System.out.println(label);
		}
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = generateLabels(QArrayList<QString;>;!QCollection<QString;>;!QCollection<QString;>;),generateObjects(I),generateWorkers(I)
 * package = tests
 * package.sourceFolder = LabelingTester/src
 * superclassType = junit.framework.TestCase
 * testCase = DSaSStressTestTest
 * testClassType = main.com.DSaSStressTest
 */