package tests.dawidSkeneTester;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import junit.framework.TestCase;
import main.com.dawidSkeneTester.TestDataGenerator;
import main.com.dawidSkeneTester.TestObjectCollection;

/**
 * The class <code>TestDataGeneratorTest</code> contains tests for the class
 * {@link <code>TestDataGenerator</code>}
 * 
 * @pattern JUnit Test Case
 * 
 * @generatedBy CodePro at 7/17/12 1:48 PM
 * 
 * @author regule
 * 
 * @version $Revision$
 */
public class TestDataGeneratorTest extends TestCase {

	/**
	 * Construct new test instance
	 * 
	 * @param name
	 *            the test name
	 */
	public TestDataGeneratorTest(String name) {
		super(name);
	}

	/**
	 * Run the ArrayList<String> generateCategoryNames(int) method test
	 */
	public void testGenerateCategoryNames() {
		System.out.println("--------AUTOMATIC CATEGORY GENERATION--------");
		TestDataGenerator fixture = new TestDataGenerator();
		int categoryCount = 10;
		ArrayList<String> result = fixture.generateCategoryNames(categoryCount);
		System.out.println(result);
	}

	/**
	 * Run the TestObjectCollection generateTestObjects(int, int) method test
	 */
	public void testGenerateTestObjectsWithEqualPercentage() {
		
		System.out.println("--------OBJECT GENERATION WITH AUTO-GENERATED CATEGORIES--------");
		TestDataGenerator fixture = new TestDataGenerator();
		int objectCount = 10000;
		int categoryCount = 4;
		TestObjectCollection result = fixture.generateTestObjects(objectCount,
				categoryCount);
		Map<String,Integer> occurences = new HashMap<String,Integer>();
		for (String object : result) {
			String category = result.getCategory(object);
			if(occurences.containsKey(category)){
				occurences.put(category, Integer.valueOf(occurences.get(category).intValue()+1));
			}else{
				occurences.put(category, Integer.valueOf(1));
			}
		}
		System.out.println("Occurences of categories in generated objects : ");
		Collection<String> categoryNames = occurences.keySet();
		for (String category : categoryNames) {
			double occ = occurences.get(category).doubleValue();
			double pr = occ/(double)objectCount;
			System.out.println(category+" : "+occ+"("+pr+")");
		}
	}

	public void testGenerateTestObjectsWithUnequalPercentage() {

		System.out.println("--------OBJECT GENERATION WITH UNEQUALLY OCCURING CATEGORIES--------");
		TestDataGenerator fixture = new TestDataGenerator();
		int objectCount = 5000;
		Map<String, Double> categories = new HashMap<String, Double>();
		categories.put("Main category (0.6)",new Double(0.6));
		categories.put("Minor category (0.3)",new Double(0.3));
		categories.put("Small category (0.1)",new Double(0.1));
		TestObjectCollection result = fixture.generateTestObjects(objectCount,
				categories);
		Map<String,Integer> occurences = new HashMap<String,Integer>();
		for (String object : result) {
			String category = result.getCategory(object);
			if(occurences.containsKey(category)){
				occurences.put(category, Integer.valueOf(occurences.get(category).intValue()+1));
			}else{
				occurences.put(category, Integer.valueOf(1));
			}
		}
		System.out.println("Occurences of categories in generated objects : ");
		Collection<String> categoryNames = occurences.keySet();
		for (String category : categoryNames) {
			double occ = occurences.get(category).doubleValue();
			double pr = occ/(double)objectCount;
			System.out.println(category+" : "+occ+"("+pr+")");
		}
		//System.out.println(result);
	}
}

/*
 * $CPS$ This comment was generated by CodePro. Do not edit it. patternId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern strategyId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = assertTrue = false callTestMethod = true createMain =
 * false createSetUp = false createTearDown = false createTestFixture = false
 * createTestStubs = false methods =
 * generateCategoryNames(I),generateTestObjects
 * (I!I),generateTestObjects(I!QMap<QString;QDouble;>;) package =
 * tests.dawidSkeneTester package.sourceFolder = LabelingTester/src
 * superclassType = junit.framework.TestCase testCase = TestDataGeneratorTest
 * testClassType = main.com.dawidSkeneTester.TestDataGenerator
 */